### ISSUE TITLE
How to use this python script ?

### ISSUE THREAD

**Issue by lucius100** [henrydatei/rapidgatorAPI#1]
How to use these script ?
I am writing my own python script to upload using their api, I failed so many times, even though my thunder bird client can access the api just fine, it seems like rapidgator is blocking python mechanism, and we need to simulate click and touch,etc. Headache.

**Comment by henrydatei** [comment]
I havn't tested this, my wrapper is still in development, but have you read the documentation? https://rapidgator.net/article/api/file#upload

**Comment by lucius100** [comment]
> I havn't tested this, my wrapper is still in development, but have you read the documentation? https://rapidgator.net/article/api/file#upload

Yes, I can upload and download via api for other filehost just fine, but rapidgator reject it so many times, don't know what mechanism they are using. I tried simple get access token, it's success via postman or thunderbird client. When I create the python script to get it, it keep saying 

{'response': None, 'status': 401, 'details': 'Error: Wrong e-mail or password.'}

even though details are correct.

**Comment by henrydatei** [comment]
Do you use my script and it doesn't work? Because I can login with my credentials without any problems.

Clone the repo and create a file inside with the following content:
```python
from rapidgatorAPI import RapidgatorAPI

rg = RapidgatorAPI("email", "password")
print(rg.info())
```

**Comment by lucius100** [comment]
> Do you use my script and it doesn't work? Because I can login with my credentials without any problems.
> 
> Clone the repo and create a file inside with the following content:
> 
> ```python
> from rapidgatorAPI import RapidgatorAPI
> 
> rg = RapidgatorAPI("email", "password")
> print(rg.info())
> ```

At the beginning,  I don't know how to use your code, so I didn't tried, and somehow this code of yours is working for me. Can you give me more example on how to do file uploading on your script ? 

Here is my simple code to get access token, you can try it

```
import requests

email = "my-email"
password = "my-password"

url = f"http://rapidgator.net/api/v2/user/login?login={email}&password={password}"

response = requests.post(url)

print(response.json())
```

my code always return {'response': None, 'status': 401, 'details': 'Error: Wrong e-mail or password.'} even though the credentials are correct.

**Comment by henrydatei** [comment]
What I think here is a problem of your usage of GET and POST and sending parameters with it. Sending parameters via url like `login?login={email}&password={password}` is possible when sending a GET request. But since you want to send a POST requests I recommend to do something like this:
```python
import requests

params = {"login": "yourEmail", "password": "yourPassword"}
r = requests.post("https://rapidgator.net/api/v2/user/login", data=params)
print(r.json())
```

**Comment by henrydatei** [comment]
You can upload with my script, I just tested it. Please pull the newest changes.

I created a file `upload_test.txt` with some text inside and ran the following code:
```python
from rapidgatorAPI import RapidgatorAPI
import hashlib
import os
import requests

rg = RapidgatorAPI("myEmail", "myPassword")
print(rg.info())

sha1 = hashlib.md5()
with open("upload_test.txt", 'rb') as f:
    while True:
        data = f.read(65536)
        if not data:
            break
        sha1.update(data)
        
size = os.path.getsize("upload_test.txt")
upload = rg.file_upload("upload_test.txt", sha1.hexdigest(), size) # prepare upload

# make upload to a URL which was specified in the previous API call
files = {'file': open('upload_test.txt', 'rb')}
r = requests.post(upload.url, files=files)

print(rg.file_upload_info(upload.upload_id)) # check the status of the upload
```

**Comment by lucius100** [comment]
> You can upload with my script, I just tested it. Please pull the newest changes.
> 
> I created a file `upload_test.txt` with some text inside and ran the following code:
> 
> ```python
> from rapidgatorAPI import RapidgatorAPI
> import hashlib
> import os
> import requests
> 
> rg = RapidgatorAPI("myEmail", "myPassword")
> print(rg.info())
> 
> sha1 = hashlib.md5()
> with open("upload_test.txt", 'rb') as f:
>     while True:
>         data = f.read(65536)
>         if not data:
>             break
>         sha1.update(data)
>         
> size = os.path.getsize("upload_test.txt")
> upload = rg.file_upload("upload_test.txt", sha1.hexdigest(), size) # prepare upload
> 
> # make upload to a URL which was specified in the previous API call
> files = {'file': open('upload_test.txt', 'rb')}
> r = requests.post(upload.url, files=files)
> 
> print(rg.file_upload_info(upload.upload_id)) # check the status of the upload
> ```

your script is giving me error, but the file uploaded to my account.
```
Traceback (most recent call last):
  File "/root/python/rapidgatorAPI/rg.py", line 22, in <module>
    r = requests.post(upload.url, files=files)
  File "/root/myenv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/root/myenv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/myenv/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/root/myenv/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/root/myenv/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/root/myenv/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

**Comment by henrydatei** [comment]
The error you see looks like something was wrong with the file_upload function and it didn't return a link. You could do a `print(upload)` to get some more information

**Comment by lucius100** [comment]
> The error you see looks like something was wrong with the file_upload function and it didn't return a link. You could do a `print(upload)` to get some more information

I will wait till u have time to develop the code, I am not that good at coding, so bunch of errors on my side.
